=== JaneOSull/DITAProject/Part1.dtd
<!ELEMENT agency_report (name, date, city, address, body, website)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT date (#PCDATA) >
<!ATTLIST date day CDATA #REQUIRED >
<!ATTLIST date month CDATA #REQUIRED >
<!ATTLIST date year CDATA #FIXED "2019" >
<!ELEMENT city (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT body (employee, employee, employee, employee?, employee?, employee?, employee?, tour, tour, tour+, finance_report)>
<!ELEMENT website (#PCDATA)>
<!ENTITY ws "www.myTravelAgency.org" >
<!ELEMENT employee (name, age, salary)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ATTLIST employee title (officer | manager | clerk | secretary | tour_leader) "officer">
<!ATTLIST employee staff_id ID #REQUIRED >
<!ATTLIST salary mode (weekly | monthly) "weekly">
<!ATTLIST salary currency CDATA #FIXED "Euro" >
<!ELEMENT tour (destination, leader+, price, date)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST tour type (domestic | international) "domestic">
<!ELEMENT destination (country, city)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT leader (#PCDATA)>
<!ATTLIST leader_id staff_id IDREF #REQUIRED>
<!ATTLIST tour mode_transport (bus | cruise | air| train) "bus">
<!ATTLIST tour tour_name ID #REQUIRED>
<!ELEMENT finance_report (fullYear | fullSeason)+>
<!ELEMENT fullYear ((trip | ticket_only)*, income)>
<!ELEMENT fullSeason ((trip | ticket_only)*, income)>
<!ELEMENT ticket_only (#PCDATA)>
<!ELEMENT income (#PCDATA)>
<!ATTLIST fullSeason seasonName ID #IMPLIED >
<!ELEMENT trip (customer, customer, customer+)>
<!ATTLIST trip trip_name IDREF "tour_name">
<!ELEMENT customer (name, age)>
<!ATTLIST customer gender (Female | Male) #IMPLIED> 
<!ENTITY ts "The total number of sold tour packages from our office has shown" >
<!ENTITY gr "To whom it may concern" >
<!ENTITY so "Yours sincerely: Cork branch" >

=== JaneOSull/DITAProject/Part3_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agency_report SYSTEM "Part1.dtd">
<agency_report> 
     <name>&gr;</name>
    <date day="" month="" year="2019"></date>
    <city></city>
    <address></address>
    <body>
        <employee staff_id="E1">
            <name></name>
            <age></age>
            <salary currency="Euro"></salary>
        </employee>
        <employee staff_id="E2">
            <name></name>
            <age></age>
            <salary currency="Euro"></salary>
        </employee>
        <employee staff_id="E3">
            <name></name>
            <age></age>
            <salary currency="Euro"></salary>
        </employee>
        <employee staff_id="E4">
            <name></name>
            <age></age>
            <salary></salary>
        </employee>
        <tour tour_name="Kerry">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <tour tour_name="Cork">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <tour tour_name="London">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <tour tour_name="Glendalough">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <tour tour_name="Galway">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <finance_report>
            <fullYear>
                <ticket_only></ticket_only>
                <trip trip_name="Kerry">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <income></income>
            </fullYear>
            <fullYear>
                <trip trip_name="Cork">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <trip trip_name="London">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <income></income>
            </fullYear>
            <fullSeason seasonName="Spring">
                <trip trip_name="Galway">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <trip trip_name="Kerry">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <trip trip_name="Kerry">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <income></income>
            </fullSeason>
        </finance_report>
    </body>
    <website></website>
</agency_report>

=== JaneOSull/DITAProject/Part3_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agency_report SYSTEM "Part1.dtd">
<agency_report>
    <name></name>
    <date day="" month="" year="2019"></date>
    <city></city>
    <address></address>
    <body>
        <employee staff_id="E1">
            <name></name>
            <age></age>
            <salary currency="Euro"></salary>
        </employee>
        <employee staff_id="E2">
            <name></name>
            <age></age>
            <salary currency="Euro"></salary>
        </employee>
        <employee staff_id="E3">
            <name></name>
            <age></age>
            <salary currency="Euro"></salary>
        </employee>
        <employee staff_id="E4">
            <name></name>
            <age></age>
            <salary></salary>
        </employee>
        <employee staff_id="E5">
            <name></name>
            <age></age>
            <salary></salary>
        </employee>
        <employee staff_id="E6">
            <name></name>
            <age></age>
            <salary></salary>
        </employee>
        <tour tour_name="Kerry" type="domestic" mode_transport="bus">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <tour tour_name="Cork" type="domestic" mode_transport="train">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <tour tour_name="London" type="international" mode_transport="air">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <tour tour_name="Glendalough" type="domestic" mode_transport="bus">
            <destination>
                <country></country>
                <city></city>
            </destination>
            <leader></leader>
            <leader></leader>
            <price></price>
            <date day="" month="" year="2019"></date>
        </tour>
        <finance_report>
            <fullYear>                
                <trip trip_name="Kerry">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <trip trip_name="Cork">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <income></income>
               </fullYear>
            <fullSeason>
                <ticket_only> </ticket_only>
                <trip trip_name="London">
                    <customer gender="Female">
                       <name></name>
                        <age></age>
                     </customer>
                     <customer gender="Female">
                        <name></name>
                        <age></age>
                    </customer>
                    <customer gender="Female">
                        <name></name>
                        <age></age>
                    </customer>
                  </trip>
                <income></income>
             
            </fullSeason>
            <fullSeason>
                <trip trip_name="Glendalough">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <income></income>
            </fullSeason>
            <fullSeason  seasonName="Winter">
                <ticket_only></ticket_only>
                <ticket_only></ticket_only>
                <trip trip_name="Kerry">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <trip trip_name="Cork">
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                    <customer>
                        <name></name>
                        <age></age>
                    </customer>
                </trip>
                <income></income>
            </fullSeason>
            
        </finance_report>
    </body>
    <website> &ws; </website>
</agency_report>
